// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMfnf3i_zgIMyhuqt4u2NGnHxzHnLdjQ',
    appId: '1:951447003589:web:8e4db5adcca8ae0dcd6bac',
    messagingSenderId: '951447003589',
    projectId: 'prjpab2-si61-2327240078',
    authDomain: 'prjpab2-si61-2327240078.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240078.firebasestorage.app',
    measurementId: 'G-8SSD6JLWRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtkSOWhlqgCTUDw-ckeer0kBAzaeUv0S4',
    appId: '1:951447003589:android:34bb4f449dd97fc7cd6bac',
    messagingSenderId: '951447003589',
    projectId: 'prjpab2-si61-2327240078',
    storageBucket: 'prjpab2-si61-2327240078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnEVtWBazGj2uC7yoK2rLpkGufPkbTQcg',
    appId: '1:951447003589:ios:7f6df5bb23f4bdadcd6bac',
    messagingSenderId: '951447003589',
    projectId: 'prjpab2-si61-2327240078',
    storageBucket: 'prjpab2-si61-2327240078.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnEVtWBazGj2uC7yoK2rLpkGufPkbTQcg',
    appId: '1:951447003589:ios:7f6df5bb23f4bdadcd6bac',
    messagingSenderId: '951447003589',
    projectId: 'prjpab2-si61-2327240078',
    storageBucket: 'prjpab2-si61-2327240078.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMfnf3i_zgIMyhuqt4u2NGnHxzHnLdjQ',
    appId: '1:951447003589:web:08a6a4b6c5b48d85cd6bac',
    messagingSenderId: '951447003589',
    projectId: 'prjpab2-si61-2327240078',
    authDomain: 'prjpab2-si61-2327240078.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240078.firebasestorage.app',
    measurementId: 'G-LBFRN0884D',
  );
}
